services:
  - type: web
    name: asm-j5
    env: docker
    plan: free
    region: singapore
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_TOOL_OPTIONS
        value: -Djava.awt.headless=true
